/* eslint-disable @next/next/no-img-element */
import dynamic from 'next/dynamic'
import Head from 'next/head'

const Greating = dynamic(() =>
  import('../components/greeting')
)
const About = dynamic(() =>
  import('../components/about')
)
const Feature = dynamic(() =>
  import('../components/feature')
)
const Technology = dynamic(() =>
  import('../components/technology')
)

export default function Home() {
  return (
    <div>
      <Head>
        <title>Tarabol</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Greating />
      <About />
      <Feature />
      <Technology />
      <section className='flex flex-col items-center bg-[#f3f4f6] pb-[24px]'>
        <div className='m-[64px] mb-[32px]'>
          <img src='logo.svg' alt='' className='w-[120px] h-[120px]'></img>
        </div>
        <p className='tracking-[1px]'>Mars is there, waiting to be reached</p>
      </section>
    </div>
  )
}
